name: Pull request workflow
on: pull_request
jobs:
  verify-ownership:
    runs-on: ubuntu-latest
    container:
      image: uwitiam/is-user-codeowner-action
    steps:
      - uses: actions/checkout@master
      - run: git fetch origin
      - run: cd /app && poetry run is-user-codeowner -u ${GITHUB_ACTOR} -p ${GITHUB_WORKSPACE} -t origin/main
